name: Release & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body: ${{steps.github_release.outputs.changelog}}

  deploy:
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/builds/captain
          git pull origin main
          git status
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh 
          npm ci
          npm run build
          pm2 restart captain
